version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  classroom:
    container_name: classroom
    image: jayinglovecoding/attendance:classroom
    restart: always
    expose:
     - "8080"
    depends_on:
      - nginx

  user:
    container_name: user
    image: jayinglovecoding/attendance:user1
    restart: always
    expose:
     - "8081"
    depends_on:
      - nginx

  rollCall:
    container_name: rollCall
    image: jayinglovecoding/attendance:rollCall1
    restart: always
    expose:
     - "8082"
    depends_on:
      - nginx

  attendanceRecord:
    container_name: attendanceRecord
    image: jayinglovecoding/attendance:record3
    restart: always
    expose:
     - "8083"
    depends_on:
      - nginx

  classEnrolled:
    container_name: classEnrolled
    image: jayinglovecoding/attendance:classEnroll3
    restart: always
    expose:
     - "8084"
    depends_on:
      - nginx

